### ISSUE TITLE
OpenVR DLL not included in Windows AppVeyor Builds

### ISSUE THREAD

**Issue by aaronvark** [hku-ect/gazebosc#183]
Either migrate to cpack and fix it there, or copy it manually in the AppVeyor YAML. The latter should be an easy fix if we can figure out where to copy it from.

**Comment by sphaero** [comment]
Still errors with cpack:

cpack -V
CPack: Enable Verbose
CPack Verbose: Read CPack config file: 
CPack Verbose: Read CPack configuration file: C:/projects/gazebosc-sphaero/build/CPackConfig.cmake
CPack Verbose: Specified generator: ZIP
CPack Verbose: Use generator: cmCPackArchiveGenerator
CPack Verbose: For project: Gazebosc
CPack: Create package using ZIP
CPack Verbose: Read description file: C:/Program Files/CMake/share/cmake-3.21/Templates/CPack.GenericDescription.txt
CPack Verbose: [ZIP] requested component grouping = ONE_PER_GROUP
CPack: Install projects
CPack: - Install project: gazebosc []
CPack Verbose: Install configuration: "Release"
CMake Error at C:/projects/gazebosc-sphaero/build/cmake_install.cmake:39 (file):
  file INSTALL cannot find
  "C:/projects/gazebosc-sphaero/build/bin/Release/gazebosc.exe": File exists.


See: https://github.com/hku-ect/gazebosc/compare/master...sphaero:cpack_win?expand=1

**Comment by aaronvark** [comment]
Maybe this relates to our problem: https://gitlab.kitware.com/cmake/cmake/-/issues/19918

Having more than one config (Debug / Release) could be causing the issue.

**Comment by sphaero** [comment]
cpack fixes this. I have it almost working. Only artefact is that gazebosc doesn't find python anymore. Can't tell why since it runs fine from the IDE and no code was changed dealing with this

**Comment by sphaero** [comment]
Somehow the pythonpath becomes "C" instead of the fullpath to where the exe is. I think this only happens in Release

**Comment by sphaero** [comment]
It's now fixed in #184
