### ISSUE TITLE
error while opening

### ISSUE THREAD

**Issue by spyrotor** [hku-ect/gazebosc#185]
Process:               gazebosc [21111]
Path:                  /Applications/gazebosc 2.app/Contents/MacOS/gazebosc
Identifier:            org.sphactor.Gazebosc
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           gazebosc [21111]
User ID:               502

Date/Time:             2021-12-01 15:54:42.971 +0100
OS Version:            macOS 11.6.1 (20G224)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        A52B251C-57EC-A533-9F61-2C178E9A70FC

Sleep/Wake UUID:       66DED149-AE71-48E0-A635-22C5E8610970

Time Awake Since Boot: 66000 seconds
Time Since Wake:       600 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 80896B32-9EB1-3A10-A7C5-449B15305DE2
Library not loaded: @rpath/libopenvr_api.dylib
  Referenced from: /Applications/gazebosc 2.app/Contents/MacOS/gazebosc
  Reason: image not found

Binary Images:
       0x10f1b3000 -        0x10f596fff +org.sphactor.Gazebosc (??? - ???) <80B9B8A7-E509-3C57-8FD7-580CFE199223> /Applications/gazebosc 2.app/Contents/MacOS/gazebosc
       0x11f589000 -        0x11f624fff  dyld (852.2) <14C5D17F-5032-37A2-9CD8-F437EB4A3992> /usr/lib/dyld

Model: MacBookPro14,3, BootROM 447.40.12.0.0, 4 processors, Quad-Core Intel Core i7, 2,8 GHz, 16 GB, SMC 2.45f5
Graphics: kHW_IntelHDGraphics630Item, Intel HD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro555Item, Radeon Pro 555, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.8)
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Apple T1 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.4

**Comment by sphaero** [comment]
This was an old version. Fixed in later versions
