### ISSUE TITLE
GUI suggestions

### ISSUE THREAD

**Issue by ikbenmacje** [hku-ect/gazebosc#192]
The possibility to be able to use:
- copy/paste/duplicate with actors (CTRL-C / CTRL-V / CTRL-D)
- The ability to select multiple actors and drag them (you can select multiple actors, but if you start to drag you will only drag one actor)

**Comment by AstridHKU** [comment]
* a comment option to keep track of what's what

**Comment by spyrotor** [comment]
- move more selected items at once

**Comment by sphaero** [comment]
some implemented here: https://github.com/rokups/ImNodes/commit/a66de84e3cf2b21bb7350be78229b9a03f6e9968

we need to merge these updates

**Comment by sphaero** [comment]
ImNodes upgrade here: https://github.com/sphaero/gazebosc/tree/ImNodesUpgr
