### ISSUE TITLE
Freaklab crash #1

### ISSUE THREAD

**Issue by AstridHKU** [hku-ect/gazebosc#194]
MidiInCore: message queue limit reached!!

I: 22-02-01 11:47:59 GOT FILE: 
Assertion failed: ((flags & 0x0F) == 0 && "Misuse of legacy hardcoded ImDrawCornerFlags values!"), function FixRectCornerFlags, file /Users/runner/work/gazebosc/gazebosc/build/imgui-1.85/imgui_draw.cpp, line 1343.
0x7ff80bb2ae2d: (_sigtramp+0x1d)
0x7ff80badf113: (__pthread_kill+0xb)
0x7ff80bb15214: (pthread_kill+0x107)
0x7ff80ba61d10: (abort+0x7b)
0x7ff80ba610be: (err+0x0)
0x10e1dfaca: (_ZL18FixRectCornerFlagsi+0x5a)
0x10e1df66f: (_ZN10ImDrawList8PathRectERK6ImVec2S2_fi+0x2f)
0x10e1dfcd5: (_ZN10ImDrawList7AddRectERK6ImVec2S2_jfif+0xf5)
0x10e268599: (_ZN7ImNodes7EndSlotEv+0x669)
0x10e2696c8: (_ZN7ImNodes2Ez4SlotEPKcib+0x488)
0x10e269835: (_ZN7ImNodes2Ez10InputSlotsEPKNS0_8SlotInfoEi+0x85)
0x10e27e25b: (_Z12UpdateActorsfPb+0x21b)
0x10e199104: (_Z6UILoopP10SDL_WindowR7ImGuiIO+0x184)
0x10e198a46: (main+0x3a6)
Gazebo version 0e6e
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Software Failure.  Please report above details.   ┃
┃            Guru Meditation #00000006               ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 11:48:07 [75602]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 11:48:07 [75602]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 11:48:07 [75602]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 11:48:07 dangling sockets: cannot terminate ZMQ safely
astrid@MacBookPro-MP11 MacOS %

**Comment by AstridHKU** [comment]
freaklab crash #2 

Assertion failed: ((flags & 0x0F) == 0 && "Misuse of legacy hardcoded ImDrawCornerFlags values!"), function FixRectCornerFlags, file /Users/runner/work/gazebosc/gazebosc/build/imgui-1.85/imgui_draw.cpp, line 1343.
0x7ff80bb2ae2d: (_sigtramp+0x1d)
0x7ff80badf113: (__pthread_kill+0xb)
0x7ff80bb15214: (pthread_kill+0x107)
0x7ff80ba61d10: (abort+0x7b)
0x7ff80ba610be: (err+0x0)
0x10e1abaca: (_ZL18FixRectCornerFlagsi+0x5a)
0x10e1ab66f: (_ZN10ImDrawList8PathRectERK6ImVec2S2_fi+0x2f)
0x10e1abcd5: (_ZN10ImDrawList7AddRectERK6ImVec2S2_jfif+0xf5)
0x10e234599: (_ZN7ImNodes7EndSlotEv+0x669)
0x10e2356c8: (_ZN7ImNodes2Ez4SlotEPKcib+0x488)
0x10e235835: (_ZN7ImNodes2Ez10InputSlotsEPKNS0_8SlotInfoEi+0x85)
0x10e24a25b: (_Z12UpdateActorsfPb+0x21b)
0x10e165104: (_Z6UILoopP10SDL_WindowR7ImGuiIO+0x184)
0x10e164a46: (main+0x3a6)
Gazebo version 0e6e
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Software Failure.  Please report above details.   ┃
┃            Guru Meditation #00000006               ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 12:12:54 [76048]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 12:12:54 [76048]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 12:12:54 [76048]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 12:12:54 [76048]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 12:12:54 [76048]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 12:12:54 [76048]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 12:12:54 [76048]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 12:12:54 [76048]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 12:12:54 [76048]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 12:12:54 [76048]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 12:12:54 [76048]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 12:12:54 [76048]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 12:12:54 [76048]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 12:12:54 [76048]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 12:12:54 [76048]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 12:12:54 [76048]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 12:12:54 [76048]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 12:12:54 dangling sockets: cannot terminate ZMQ safely
Assertion failed: false (src/object.cpp:455)
0x7ff80bb2ae2d: (_sigtramp+0x1d)
0x7ff80badf113: (__pthread_kill+0xb)
Gazebo version 0e6e
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Software Failure.  Please report above details.   ┃
┃            Guru Meditation #00000006               ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
astrid@MacBookPro-MP11 ~ %

**Comment by AstridHKU** [comment]
aanleiding Crash #2 : "OSC in" verbinden aan "Record"

**Comment by sphaero** [comment]
Source:

```
// If this triggers, please update your code replacing hardcoded values with new ImDrawFlags_RoundCorners* values.
    // Note that ImDrawFlags_Closed (== 0x01) is an invalid flag for AddRect(), AddRectFilled(), PathRect() etc...
    IM_ASSERT((flags & 0x0F) == 0 && "Misuse of legacy hardcoded ImDrawCornerFlags values!");
```

**Comment by sphaero** [comment]
This happens because we hacked into ImNodes @aaronvark  We need to merge upstream changes in ImNodes

**Comment by sphaero** [comment]
It is fixed with upstream changes. But we can't connect anymore
