### ISSUE TITLE
Update README liblo version >= 0.30 works on Linux

### ISSUE THREAD

**Issue by PanderMusubi** [hku-ect/gazebosc#23]
Update README that liblo version >= 0.30 works on Linux

**Comment by PanderMusubi** [comment]
Another small improvement for the README `The UI based on ImGui,` should be `The UI is based on ImGui,`

**Comment by sphaero** [comment]
Liblo has been replaced by [zosc](https://github.com/zeromq/czmq/blob/master/src/zosc.c)
