### ISSUE TITLE
Float Slider picture 'f' is incorrect

### ISSUE THREAD

**Issue by aaronvark** [hku-ect/gazebosc#244]
The Float Slider actor tries to set its value using the 'f' picture, but zsock_send implements this as "zframe_t", not float.

There is currently no float picture implemented that I can see, so we could either convert back and forth to some supported type, or implement float.

**Comment by sphaero** [comment]
I don't know what happened. I had the float slider working with a fix but I kinda lost the hack???

**Comment by sphaero** [comment]
Ok, I think I forgot to merge this in libsphactor and I tossed the branch :cry: 

This can be fixed in sphactor_ask_api* calls by just changing the format char to s and the the float value to ascii. This is actually not uncommon for floats
