### ISSUE TITLE
Support z25 LED controller

### ISSUE THREAD

**Issue by PanderMusubi** [hku-ect/gazebosc#25]
Please support z25 LED controller.

The `pattern` input is the normal input and consists of RGB values for all individual LEDs. The `all` input is for setting all e.g. to black and takes only one RGB value. The `test` input is to start a test pattern to see the direction of how the LED strip is mounted and if any LEDs are faulty. This input will be triggered when receiving a value of `1`.

![z25-ledcontroller](https://user-images.githubusercontent.com/198964/70600879-1fa1ff00-1bf1-11ea-9e7b-e735f7f21c8a.png)

The code below is for PlantUML and contains non-breaking spaces.

    @startsalt
    {^<b>z25 LED controller
      IP address | "10.0.0.1" | *
      --|--|--
      (X) pattern |   <b>STRIP 1
      (X) all     |        test | (X)
      --|--|--
      (X) pattern |   <b>STRIP 2
      (X) all     |        test | (X)
      --|--|--
      (X) pattern |   <b>STRIP 3
      (X) all     |        test | (X)
      --|--|--
      (X) pattern |   <b>STRIP 4
      (X) all     |        test | (X)
      --|--|--
      (X) pattern |   <b>STRIP 5
      (X) all     |        test | (X)
      --|--|--
      (X) pattern |   <b>STRIP 6
      (X) all     |        test | (X)
      --|--|--
      (X) pattern |   <b>STRIP 7
      (X) all     |        test | (X)
      --|--|--
      (X) pattern |   <b>STRIP 8
      (X) all     |        test | (X)
      --|--|--
    }
    @endsalt

**Comment by sphaero** [comment]
We don't have access to a controller so closing this as these devices are bit of the past?
