### ISSUE TITLE
Build on latest raspberry pi os fails

### ISSUE THREAD

**Issue by sphaero** [hku-ect/gazebosc#265]
They are not using the the legacy bcm drivers anymore. Switched to KMS which uses just mesa libs I guess

See in imgui PR https://github.com/ocornut/imgui/pull/2837

**Comment by sphaero** [comment]
Got it working on latest raspberry pi os. Needs minor tweaking in the CMakeLists.txt

**Comment by sukesh-ak** [comment]
> Got it working on latest raspberry pi os. Needs minor tweaking in the CMakeLists.txt

Are you running it with the Desktop or with RPI Lite version of the OS?

**Comment by sphaero** [comment]
Rpi lite

**Comment by sphaero** [comment]
Is that even connected to the gpu?

**Comment by sphaero** [comment]
fixed in #271
