### ISSUE TITLE
Gazebo build 647024b from build bot: gazebosc_OSX_10.15_6470.dmg does not run

### ISSUE THREAD

**Issue by ikbenmacje** [hku-ect/gazebosc#296]
I tried to run by double clicking the app this did not work with no feedback. I then tried to run gazebo from terminal and got the following output:

machiel: gazebosc.app % cd Contents/MacOS
machiel: MacOS % ls
gazebosc
machiel: MacOS % ./gazebosc
I: 23-09-27 13:35:52 working dir changed to /Users/machiel/Downloads/gazebosc.app/Contents/Resources
I: 23-09-27 13:35:52 Resources dir is /Users/machiel/Downloads/gazebosc.app/Contents/Resources
I: 23-09-27 13:35:52 Tmp dir is /private/var/folders/rl/fwtvkjw17r58g0_t6tzrlh7w0000gq/T
Python path configuration:
  PYTHONHOME = '/Users/machiel/Downloads/gazebosc.app/Contents/Resources/python'
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/Users/machiel/Downloads/gazebosc.app/Contents/MacOS/./gazebosc'
  sys.base_prefix = '/Users/machiel/Downloads/gazebosc.app/Contents/Resources/python'
  sys.base_exec_prefix = '/Users/machiel/Downloads/gazebosc.app/Contents/Resources/python'
  sys.platlibdir = 'lib'
  sys.executable = '/Users/machiel/Downloads/gazebosc.app/Contents/MacOS/./gazebosc'
  sys.prefix = '/Users/machiel/Downloads/gazebosc.app/Contents/Resources/python'
  sys.exec_prefix = '/Users/machiel/Downloads/gazebosc.app/Contents/Resources/python'
  sys.path = [
    '/Users/machiel/Downloads/gazebosc.app/Contents/Resources/python/lib/python39.zip',
    '/Users/machiel/Downloads/gazebosc.app/Contents/Resources/python/lib/python3.9',
    '/Users/machiel/Downloads/gazebosc.app/Contents/Resources/python/lib/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

**Comment by sphaero** [comment]
fixed
